### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hanxiansheng26** [broken5/WebAliveScan#1]
Traceback (most recent call last):
  File "webscan.py", line 26, in <module>
    fire.Fire(run)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "webscan.py", line 22, in run
    main = Program(target, port, brute)
  File "webscan.py", line 12, in __init__
    save_result(request.alive_path, ['title', 'url', 'status', 'size', 'reason'], request.alive_result_list)
  File "H:\tool\vstart\tools\information collect\WebAliveScan-master\lib\utils\tools.py", line 8, in save_result
    f_csv.writerows(results)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2665' in position 13: illegal multibyte sequence

**Comment by cangqingzhe** [comment]
我这也有这个错，中文编码的问题吧

**Comment by broken5** [comment]
最新版也存在这个问题吗

**Comment by cangqingzhe** [comment]
使用最新版的虽然不报错了，但是导出的csv里面中文是乱码

**Comment by cangqingzhe** [comment]
使用最新版的虽然不报错了，但是导出的csv里面中文是乱码,我测试时发现可以WebAliveScan\lib\utils下的tools.py中utf-8编码那去掉可以正常输出，不过不知道抑制报错后，错误后面的内容能不能正常输出
