### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by dogdie233** [broken5/WebAliveScan#5]
PS F:\Python\WebAliveScan-master> python .\webscan.py --target .\target.txt
Traceback (most recent call last):
  File ".\webscan.py", line 1, in <module>
    from lib.common.request import Request
  File "F:\Python\WebAliveScan-master\lib\common\request.py", line 1, in <module>
    from gevent import monkey, pool; monkey.patch_all()
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\gevent\__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\gevent\_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 144 from PyObject

**Comment by dropslzx** [comment]
我也碰到了这种情况，请问有解决的办法吗？

**Comment by dropslzx** [comment]
py3.8.6发现解决办法，可以用gevent==1.5.0解决
【https://pypi.tuna.tsinghua.edu.cn/packages/47/6a/1b4b009e2568c6c429a22db6c786391969a877a1d67ff1209603fad3c8f2/gevent-1.5.0-cp38-cp38-win_amd64.whl#sha256=45a5af965cc969dd06128740f5999b9bdb440cb0ba4e9c066e5c17a2c33c89a8】
