### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by B4Jewer** [broken5/WebAliveScan#6]
Traceback (most recent call last):
  File "webscan.py", line 31, in <module>
    fire.Fire(run)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "webscan.py", line 27, in run
    main = Program(target, port, brute)
  File "webscan.py", line 13, in __init__
    request = Request(target, port, output, wappalyzer)
  File "/root/WebAliveScan/lib/common/request.py", line 17, in __init__
    self.url_list = self.gen_url_list(target, port)
  File "/root/WebAliveScan/lib/common/request.py", line 67, in gen_url_list
    domain, port = domain.split(':')
ValueError: too many values to unpack (expected 2)

**Comment by broken5** [comment]
你的target文件格式有问题
